### ISSUE TITLE
KeyError: 'streamingData'

### ISSUE THREAD

**Issue by xxCryptoxx** [xxCryptoxx/pychan#2]
So for some videos on youtube, pytube issues an error.

```
Traceback (most recent call last):
  File "c\pychan.py", line 100, in <module>
    main(counter)
  File "c\pychan.py", line 42, in main
    audio.streams.get_audio_only().download()
  File "C:\Users\c\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\c\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 172, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\c\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 157, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'
```

**Comment by xxCryptoxx** [comment]
```
except KeyError as key:
    print(key)
```
